"""empty message

Revision ID: 622a2ad64973
Revises: 93068451b88b
Create Date: 2025-04-24 14:40:54.029929

"""
import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = '622a2ad64973'
down_revision = '93068451b88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
            batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True, server_default=str(datetime.datetime.now(tz=datetime.timezone.utc))))
            batch_op.add_column(sa.Column('last_modif', sa.DateTime(), nullable=True, server_default=str(datetime.datetime.now(tz=datetime.timezone.utc))))
            batch_op.create_index(batch_op.f('ix_case__misp__object_creation_date'), ['creation_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_case__misp__object_last_modif'), ['last_modif'], unique=False)
    except OperationalError:
        print("Column already exist in 'case__misp__object'")

    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True, server_default=str(datetime.datetime.now(tz=datetime.timezone.utc))))
            batch_op.add_column(sa.Column('last_modif', sa.DateTime(), nullable=True, server_default=str(datetime.datetime.now(tz=datetime.timezone.utc))))
            batch_op.create_index(batch_op.f('ix_misp__attribute_creation_date'), ['creation_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_misp__attribute_last_modif'), ['last_modif'], unique=False)
    except OperationalError:
        print("Columns already exist in 'misp__attribute'")

    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True, server_default=str(datetime.datetime.now(tz=datetime.timezone.utc))))
            batch_op.create_index(batch_op.f('ix_user_creation_date'), ['creation_date'], unique=False)
    except OperationalError:
        print("Column 'creation_date' already exist in 'user'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_user_creation_date'))
            batch_op.drop_column('creation_date')
    except OperationalError:
        print("Column 'creation_date' already dropped from 'user'")

    try:
        with op.batch_alter_table('misp__attribute', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_misp__attribute_last_modif'))
            batch_op.drop_index(batch_op.f('ix_misp__attribute_creation_date'))
            batch_op.drop_column('last_modif')
            batch_op.drop_column('creation_date')
    except OperationalError:
        print("Columns already dropped from 'misp__attribute'")

    try:
        with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_case__misp__object_last_modif'))
            batch_op.drop_index(batch_op.f('ix_case__misp__object_creation_date'))
            batch_op.drop_column('last_modif')
            batch_op.drop_column('creation_date')
    except OperationalError:
        print("Columns already dropped from 'case__misp__object'")

    # ### end Alembic commands ###
