"""empty message

Revision ID: b517c582523f
Revises: 8626dbc8e984
Create Date: 2024-09-25 11:39:24.206964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'b517c582523f'
down_revision = '8626dbc8e984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
            batch_op.drop_index('ix_case__template__connector__instance_instance_id')
            batch_op.drop_index('ix_case__template__connector__instance_template_id')
    except OperationalError:
        print("Index already dropped")

    try:
        op.drop_table('case__template__connector__instance')
    except OperationalError:
        print("Table 'case__template__connector__instance' already dropped")

    try:
        op.drop_table('_alembic_tmp_case__misp__object')
    except OperationalError:
        print("Table '_alembic_tmp_case__misp__object' already dropped")

    try:
        with op.batch_alter_table('task__template__connector__instance', schema=None) as batch_op:
            batch_op.drop_index('ix_task__template__connector__instance_instance_id')
            batch_op.drop_index('ix_task__template__connector__instance_template_id')
    except OperationalError:
        print("Index already dropped")

    try:
        op.drop_table('task__template__connector__instance')
    except OperationalError:
        print("Table 'task__template__connector__instance' already dropped")

    try:
        op.drop_table('_alembic_tmp_task')
    except OperationalError:
        print("Table '_alembic_tmp_task' already dropped")
    
    with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
        batch_op.alter_column('case_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case__misp__object', schema=None) as batch_op:
        batch_op.alter_column('case_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    try:
        op.create_table('_alembic_tmp_task',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('uuid', sa.VARCHAR(length=36), nullable=True),
        sa.Column('title', sa.VARCHAR(), nullable=True),
        sa.Column('description', sa.VARCHAR(), nullable=True),
        sa.Column('url', sa.VARCHAR(), nullable=True),
        sa.Column('creation_date', sa.DATETIME(), nullable=True),
        sa.Column('deadline', sa.DATETIME(), nullable=True),
        sa.Column('last_modif', sa.DATETIME(), nullable=True),
        sa.Column('finish_date', sa.DATETIME(), nullable=True),
        sa.Column('case_id', sa.INTEGER(), nullable=True),
        sa.Column('status_id', sa.INTEGER(), nullable=True),
        sa.Column('completed', sa.BOOLEAN(), nullable=True),
        sa.Column('notif_deadline_id', sa.INTEGER(), nullable=True),
        sa.Column('case_order_id', sa.INTEGER(), nullable=True),
        sa.Column('nb_notes', sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(['case_id'], ['case.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    except OperationalError:
        print("Table '_alembic_tmp_task' already exist")

    try:
        op.create_table('task__template__connector__instance',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('template_id', sa.INTEGER(), nullable=True),
        sa.Column('instance_id', sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    except OperationalError:
        print("Table 'task__template__connector__instance' already exist")
    
    try:
        with op.batch_alter_table('task__template__connector__instance', schema=None) as batch_op:
            batch_op.create_index('ix_task__template__connector__instance_template_id', ['template_id'], unique=False)
            batch_op.create_index('ix_task__template__connector__instance_instance_id', ['instance_id'], unique=False)
    except OperationalError:
        print("Index already exist")

    try:
        op.create_table('_alembic_tmp_case__misp__object',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('case_id', sa.INTEGER(), nullable=True),
        sa.Column('template_uuid', sa.VARCHAR(length=36), nullable=True),
        sa.Column('name', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    except OperationalError:
        print("Table '_alembic_tmp_case__misp__object' already exist")

    try:
        op.create_table('case__template__connector__instance',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('template_id', sa.INTEGER(), nullable=True),
        sa.Column('instance_id', sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    except OperationalError:
        print("Table 'case__template__connector__instance' already exist")

    try:
        with op.batch_alter_table('case__template__connector__instance', schema=None) as batch_op:
            batch_op.create_index('ix_case__template__connector__instance_template_id', ['template_id'], unique=False)
            batch_op.create_index('ix_case__template__connector__instance_instance_id', ['instance_id'], unique=False)
    except OperationalError:
        print("Index already exist")

    # ### end Alembic commands ###
